require('settings')
require('bindings')
require('plugins.package_manager')
require('plugins.file_search')
require('plugins.file_tree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.debugger')
